Repository Izroth404/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#22 Create partitionList.java
  Java_programs/partitionList.java
Labels: HACKTOBERFEST-ACCEPTED

#21 Create copyListwithRandomPointer.java
  Java_programs/copyListwithRandomPointer.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#20 Create reorderList.java
  reorderList.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#19 Create flattenaMultilevelDoublyLinkedList.java
  flattenaMultilevelDoublyLinkedList.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED

#18 Java Polymorphism
  Polymorphism/Demo.class
  Polymorphism/compoly.class
  Polymorphism/compoly.java
  Polymorphism/runpoly.class
  Polymorphism/runpoly.java
  Polymorphism/square.class
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#17 Create linkedListCycle.java
  Java_programs/linkedListCycle.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#30 commits from priyam
  Java_programs/fibonacci2.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#31 Priyam
  Java_programs/subset.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#32 3rd commit from priyam
  Java_programs/goldmine.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#33 4th commit from priyam
  Java_programs/Palindrome.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#41 Create TwoSum.java
  Java_programs/TwoSum.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#40 Create Armstrong.java
  Java_programs/Armstrong.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#39 HACKTOBERFEST2022
  DSA.JAVA4321
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#38 Added TrailingZero Solution
  Java_programs/TrailingZeroInFactorial.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#37 dublicate
  Java_programs/dublicate.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#36 Added Frequency program
  Java_programs/frequency.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#35 Hacktoberfest
  Java.2python
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#34 Created C++ programs
  C++/Heap.cpp
  C++/Kruskal_Graph.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#49 hacktoberfest2022
  classobject.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#48 hacktoberfest2022
  Java_programs/find_determinant.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#47 Maximum sum subarray.java
  kadanes_algorithm.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#46 Create Recursion.py
  Recursion.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#45 Problem solving in java
  Java_programs/Leaders.java
  Java_programs/key.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#44 Hacktoberfest2022
  Python/password.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#55 Running Leetcode Java solutions with problem numbers
  Java_programs/144.Binary_Tree_Preorder_Traversal.java
  Java_programs/145.Binary_Tree_Postorder_Traversal.java
  Java_programs/24.Swap_Nodes_in_Pairs.java
  Java_programs/27.Remove_Element.java
  Java_programs/94.Binary_Tree_Inorder_Traversal.java
  Java_programs/98. Validate Binary Search Tree.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#54 linked_list_insertion
  C++/linked_list_insertion/insert_at_beg.cpp
  C++/linked_list_insertion/inserting.cpp
  C++/linked_list_insertion/insertion_at_pos.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#53 hacktoberfest2022
  Java_programs/SelectionSortAlgorithmEx.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#52 Create Card rempval Problem Codechef
  Card rempval Problem Codechef
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#50 Added Math_MaxAndMin in java_programs
  Java_programs/Math_MaxAndMin.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#51 Create warshall.java
  Java_programs/warshall.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#59 Code for sieve of erathos algorithm
  Java_programs/BinarySearch.java
  Java_programs/SieveOfErathos.java
  Java_programs/TowerOfHanoi.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#60 Added 2 programs to Java folder and correction to README.md
  Java_programs/CarLoanRepayment.java
  Java_programs/FizzBuzz.java
  README.md
Labels: good first issue, hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#63 added program to find LCM
  Java_programs/LCM.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#62 Repo Maintenance
  Java_programs/Card removal Problem Codechef
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#66 Create Translator.py
  Python/Translator.py
  Python/Typing_speed_test.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#67 Create MergeSort.py
  Python/MergeSort.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#69 Create stack queue interface
  stack queue interface
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#68 Create quizGame.py
  Python/quizGame.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#71 Hacktoberfest2022
  Python/lightshow.py
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#74 Longest Palindromic Substring.java
  Java_programs/Median of Two Sorted Arrays.java
  Longest Palindromic Substring.java
  Merge k Sorted Lists.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#73 Added Binary Tree Max Path Sum
  C++/124_BinaryTreeMaximumPathSum.cpp
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#72 Valid Parenthesis
  Abstraction/MyAbstractClass.java
  Abstraction/Rider.java
  Java_programs/ValidParenthesis.java
Labels: hacktoberfest2022, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022
